./filler_vm -p1 players/a.out -p2 players/abanlin.filler -v -f maps/map02 > 1.txt
./filler_vm -p1 players/a.out -p2 players/abanlin.filler -v -f maps/map02 > 2.txt
./filler_vm -p1 players/a.out -p2 players/abanlin.filler -v -f maps/map02 > 3.txt
./filler_vm -p1 players/a.out -p2 players/abanlin.filler -v -f maps/map02 > 4.txt
./filler_vm -p1 players/a.out -p2 players/abanlin.filler -v -f maps/map02 > 5.txt
./filler_vm -p1 players/a.out -p2 players/abanlin.filler -v -f maps/map02 > 6.txt
./filler_vm -p1 players/a.out -p2 players/abanlin.filler -v -f maps/map02 > 7.txt
./filler_vm -p1 players/a.out -p2 players/abanlin.filler -v -f maps/map02 > 8.txt
./filler_vm -p1 players/a.out -p2 players/abanlin.filler -v -f maps/map02 > 9.txt
./filler_vm -p1 players/a.out -p2 players/abanlin.filler -v -f maps/map02 > 10.txt
./filler_vm -p1 players/abanlin.filler -p2 players/a.out -v -f maps/map02 > a.txt
./filler_vm -p1 players/abanlin.filler -p2 players/a.out -v -f maps/map02 > b.txt
./filler_vm -p1 players/abanlin.filler -p2 players/a.out -v -f maps/map02 > c.txt
./filler_vm -p1 players/abanlin.filler -p2 players/a.out -v -f maps/map02 > d.txt
./filler_vm -p1 players/abanlin.filler -p2 players/a.out -v -f maps/map02 > e.txt
./filler_vm -p1 players/abanlin.filler -p2 players/a.out -v -f maps/map02 > f.txt
./filler_vm -p1 players/abanlin.filler -p2 players/a.out -v -f maps/map02 > g.txt
./filler_vm -p1 players/abanlin.filler -p2 players/a.out -v -f maps/map02 > h.txt
./filler_vm -p1 players/abanlin.filler -p2 players/a.out -v -f maps/map02 > j.txt
