./filler_vm -p1 players/a.out -p2 players/carli.filler -v -f maps/map01 > 1.txt
./filler_vm -p1 players/a.out -p2 players/carli.filler -v -f maps/map01 > 2.txt
./filler_vm -p1 players/a.out -p2 players/carli.filler -v -f maps/map01 > 3.txt
./filler_vm -p1 players/a.out -p2 players/carli.filler -v -f maps/map01 > 4.txt
./filler_vm -p1 players/a.out -p2 players/carli.filler -v -f maps/map01 > 5.txt
./filler_vm -p1 players/a.out -p2 players/carli.filler -v -f maps/map01 > 6.txt
./filler_vm -p1 players/a.out -p2 players/carli.filler -v -f maps/map01 > 7.txt
./filler_vm -p1 players/a.out -p2 players/carli.filler -v -f maps/map01 > 8.txt
./filler_vm -p1 players/a.out -p2 players/carli.filler -v -f maps/map01 > 9.txt
./filler_vm -p1 players/a.out -p2 players/carli.filler -v -f maps/map01 > 10.txt
./filler_vm -p1 players/a.out -p2 players/carli.filler -v -f maps/map02 > 11.txt
./filler_vm -p1 players/a.out -p2 players/carli.filler -v -f maps/map02 > 12.txt
./filler_vm -p1 players/a.out -p2 players/carli.filler -v -f maps/map02 > 13.txt
./filler_vm -p1 players/a.out -p2 players/carli.filler -v -f maps/map02 > 14.txt
./filler_vm -p1 players/a.out -p2 players/carli.filler -v -f maps/map02 > 15.txt
./filler_vm -p1 players/a.out -p2 players/carli.filler -v -f maps/map02 > 16.txt
./filler_vm -p1 players/a.out -p2 players/carli.filler -v -f maps/map02 > 17.txt
./filler_vm -p1 players/a.out -p2 players/carli.filler -v -f maps/map02 > 18.txt
./filler_vm -p1 players/a.out -p2 players/carli.filler -v -f maps/map02 > 19.txt
./filler_vm -p1 players/a.out -p2 players/carli.filler -v -f maps/map02 > 20.txt
./filler_vm -p1 players/a.out -p2 players/carli.filler -v -f maps/map02 > 21.txt

