./filler_vm -p1 players/a.out -p2 players/superjeannot.filler -v -f maps/map02 >> 1.txt
./filler_vm -p1 players/a.out -p2 players/superjeannot.filler -v -f maps/map02 >> 2.txt
./filler_vm -p1 players/a.out -p2 players/superjeannot.filler -v -f maps/map02 >> 3.txt
./filler_vm -p1 players/a.out -p2 players/superjeannot.filler -v -f maps/map02 >> 4.txt
./filler_vm -p1 players/a.out -p2 players/superjeannot.filler -v -f maps/map02 >> 5.txt
./filler_vm -p1 players/a.out -p2 players/superjeannot.filler -v -f maps/map02 >> 6.txt
./filler_vm -p1 players/a.out -p2 players/superjeannot.filler -v -f maps/map02 >> 7.txt
./filler_vm -p1 players/a.out -p2 players/superjeannot.filler -v -f maps/map02 >> 8.txt
./filler_vm -p1 players/a.out -p2 players/superjeannot.filler -v -f maps/map02 >> 9.txt
./filler_vm -p1 players/a.out -p2 players/superjeannot.filler -v -f maps/map02 >> 10.txt
./filler_vm -p1 players/superjeannot.filler -p2 players/a.out -v -f maps/map02 >> 11.txt
./filler_vm -p1 players/superjeannot.filler -p2 players/a.out -v -f maps/map02 >> 12.txt
./filler_vm -p1 players/superjeannot.filler -p2 players/a.out -v -f maps/map02 >> 13.txt
./filler_vm -p1 players/superjeannot.filler -p2 players/a.out -v -f maps/map02 >> 14.txt
./filler_vm -p1 players/superjeannot.filler -p2 players/a.out -v -f maps/map02 >> 15.txt
./filler_vm -p1 players/superjeannot.filler -p2 players/a.out -v -f maps/map02 >> 16.txt
./filler_vm -p1 players/superjeannot.filler -p2 players/a.out -v -f maps/map02 >> 17.txt
./filler_vm -p1 players/superjeannot.filler -p2 players/a.out -v -f maps/map02 >> 18.txt
./filler_vm -p1 players/superjeannot.filler -p2 players/a.out -v -f maps/map02 >> 19.txt
